apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  targetNamespace: flux-system
  values:
    adminUser:
      create: true
      username: admin
      # Password hash for 'admin' - you should change this!
      # Generate with: echo -n "your-password" | gitops get bcrypt-hash
      passwordHash: $2a$10$P/tHQ1DNFXdvX0zRGA8LPeSOyb0JXq9rP3fZ4W8HGTpLV7qHDlWhe
