apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka
      version: "26.11.4"  # Using Kafka 3.6.1 for better ARM32 support
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: kafka
  install:
    createNamespace: true
  values:
    # Disable KRaft mode - use ZooKeeper for ARM32 compatibility
    kraft:
      enabled: false

    # Disable authentication to simplify deployment
    auth:
      clientProtocol: plaintext
      interBrokerProtocol: plaintext

    # Kafka configuration - use extraConfig instead of config
    extraConfig: |
      log.retention.hours=168
      log.retention.bytes=1073741824
      log.segment.bytes=104857600
      log.cleanup.policy=delete
      compression.type=snappy
      auto.create.topics.enable=true
      default.replication.factor=1
      min.insync.replicas=1

    # Configure brokers for ZooKeeper mode
    broker:
      replicaCount: 1
      persistence:
        enabled: true
        storageClass: local-path
        size: 5Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi

    # Service configuration
    service:
      type: ClusterIP
      ports:
        client: 9092

    # Disable controller nodes (only for KRaft mode)
    controller:
      replicaCount: 0

    # Metrics exporter for Prometheus
    metrics:
      kafka:
        enabled: true
        service:
          port: 9308
      jmx:
        enabled: true
        service:
          port: 5556

    # Enable ZooKeeper with minimal resources
    zookeeper:
      enabled: true
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      persistence:
        enabled: true
        storageClass: local-path
        size: 2Gi
