apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  - port: 2181
    name: zookeeper
    targetPort: 2181
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: johnnypark/kafka-zookeeper
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 2181
          name: zookeeper
        env:
        - name: ADVERTISED_HOST
          value: "kafka.kafka.svc.cluster.local"
        - name: ADVERTISED_PORT
          value: "9092"
        - name: AUTO_CREATE_TOPICS
          value: "true"
        - name: NUM_PARTITIONS
          value: "3"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
