apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
  targetNamespace: loki
  install:
    createNamespace: true
  values:
    loki:
      enabled: true
      image:
        tag: 2.4.2  # Use older version compatible with ARM32
      persistence:
        enabled: true
        storageClassName: local-path
        size: 5Gi
      config:
        auth_enabled: false
        limits_config:
          retention_period: 48h  # 2 days
          reject_old_samples: true
          reject_old_samples_max_age: 48h

    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki-loki:3100/loki/api/v1/push
        positions:
          filename: /tmp/positions.yaml
        scrape_configs:
          # Scrape all pods
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node_name
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - source_labels: [__meta_kubernetes_pod_label_app]
                target_label: app

    grafana:
      enabled: false  # We already have Grafana deployed

    prometheus:
      enabled: false  # We already have Prometheus deployed
