---
# Self-signed ClusterIssuer for internal services
# Certificates are trusted within the cluster and local network
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}

---
# CA Issuer - Creates a CA certificate that can sign other certificates
# This provides a more structured certificate hierarchy
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair

---
# Self-signed certificate for the CA
# This creates the root CA certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: cert-manager
spec:
  isCA: true
  commonName: cluster-ca
  secretName: ca-key-pair
  duration: 87600h  # 10 years
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
