---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-grafana
  namespace: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy-grafana
  ports:
  - port: 4180
    targetPort: 4180
    protocol: TCP
  type: ClusterIP
