apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
  targetNamespace: longhorn-system
  install:
    createNamespace: true
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      storageMinimalAvailablePercentage: 10
