apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '>=2.0.0'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # ARM32 compatible configuration
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

    # Increase probe delays for slower ARM32 startup
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 10
