---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
spec:
  encryptedData:
    password: AgBYCC5PImB+AjgTEd1YJFHmdbN9uzaQNp5+ITycp80Wn2UMF/oEGh6p1VQmZxGHkSDbvpjyJpjiQt5Cyy8KU/z7n4wt6Nzre7MD4s4x/Uji387B0Zod4WkDmPM50K1lP7Uy3xPrIyEVzelx5sJ8W4tHZNK36McuE4d79gvhtL7jfZ4NeXWgTRj4cZxchPNu8uVheOYHtT59Il08CyKPTC8QYZYaGEu0yYVvzTHWM0qVVlpTAWLrUpbpYgiTi1bPNhBy70FQNXXBOtzKFBOV1AHpKDBhWz7SBgpbo0UkabW37hhqnVPL3kDW07sqhz01Bh8c4qcpRyRPGIAL9fpwX9MpaLrXdB1MWtPa2a0oXuZa+WpsQFVrp2ZkUwGJKdzJPh4cT4OWA/jpdHRMPWX8nt4aknrG21MnYnuV/wPDhZ2TrKe0kj7o0sw0cncA+qbTiiuN/fqnngasqg8sune5mVCp9PjAwf6sXHUgm0sgGResuNLvC/9V8pPlcq8UtGba/iM1C/zR9+8uTQUxK3y9zsdX+VBkP6jidpz+FU4zeJAUTHt5dlPgAhnmvzLV5XaO8YdPuY4KckdKXjYtgYGT7LHRKigJjU3didddMGUOg0YHJvopBUCA4cgjM2B6TjTVomPV/fYST21VOvOgKFZuRfTa6uIuLtvv3EZAZT6iIVHhQaEa4++mHCegxC/K6Vnm9pJPA2pCzilXtg==
    username: AgCjXOssCmppHZhAtTudQrqx3WAA2x23KOGRdo2+B48AEithk5gZQufP58we7JULRU6vbISPBTZIklobz2qQX9LYM1hxVSxfNyWhfr6W29qaMOpYd42fPR8CeXQtWPMAMLDBeBxiiFQJnCcw5qeFT62WwikJ71wdhoRo2P+w9Cg10IA9vvWMx7ztC6OSJ5nWyPHfOAttxMc/vR3h8K/q1ewskZunclpifm7oJroMXtoXGcceNPb4CupmWxBmK/+pApu1MildDrvmJjXGn8a8uw5rjlEtfI8+dis3ICyHt5WeXlRKX/ar0uyN6R2sjd1HYMH51Gd+QV+NAzg5RUrbtFOG2blgMi9KcO8Sjk7kMfgbv2b77YZhYldOwyCKmNhcIAcjPHnkl7PWYnonMW77Y4mL8HjfW9Rwmtcn+zlVRL4xDKskCEXC38EE8Nu+RPKI8zvCbVcF9W+Y6uARjhVCkpfw0SSCGklXHy7w5F7fvbg/LsQuQq9Bzt+RnCJziKYSGhEnu+pxaUNXe/PIM/M73ZkiN8skqIjaY/nsCo9XHJ70MvHT8+XmgYSJ8OAG3h7I/jUBlmzE/dBzjqO5H7+Srp69ZeXrQEqQ8yk05sqwqqetjey7SmCXbUmYkttt4RStJi3lRXpzFuD570lFeOj6lA8pUxAayU2FyPb1e0tMR9gKb3u14WpBqjUOC5CVVl8a+DXGSogA1g==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: rabbitmq
    type: Opaque
