---
# Tekton Pipelines Installation
# This applies the official Tekton Pipelines release manifest
# Note: For production, you would typically vendor these manifests or use a Helm chart
# For this setup, we'll apply via a one-time kubectl command and manage via Flux afterwards

# The official installation command is:
# kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.55.0/release.yaml

# For ARM32 (Raspberry Pi) compatibility, Tekton v0.55.0+ includes multi-arch images
# We'll create a ConfigMap with installation instructions and apply manually first time

apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-install-instructions
  namespace: tekton-pipelines
data:
  README.txt: |
    Tekton Pipelines Installation Instructions
    ==========================================

    Due to the size of the Tekton manifests, they are best installed directly from the official release.

    Run these commands to install Tekton:

    # 1. Install Tekton Pipelines (Core)
    kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.55.0/release.yaml

    # 2. Verify installation
    kubectl get pods -n tekton-pipelines

    # Expected pods:
    # - tekton-pipelines-controller
    # - tekton-pipelines-webhook

    # 3. Install Tekton Dashboard (Optional, for Web UI)
    kubectl apply -f https://storage.googleapis.com/tekton-releases/dashboard/previous/v0.43.0/release.yaml

    # 4. Verify dashboard
    kubectl get pods -n tekton-pipelines

    # Expected additional pod:
    # - tekton-dashboard

    After installation, Flux will manage the Pipeline, Task, and Trigger resources.
