---
# Tekton Pipelines - Core CI/CD engine
# This manifest references the official Tekton Pipelines release
# ARM32 compatible images are automatically selected
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tekton-pipelines
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/tektoncd/pipeline
  ref:
    tag: v0.55.0  # Latest stable release
  ignore: |
    /*
    !/config/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-pipelines
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: tekton-pipelines
  path: ./config
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-pipelines-controller
      namespace: tekton-pipelines
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-pipelines-webhook
      namespace: tekton-pipelines
