---
# Pipeline: SmartBiz CI/CD
# Complete pipeline for building, testing, and deploying SmartBiz API
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: smartbiz-cicd
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: smartbiz-cicd
spec:
  description: |
    Complete CI/CD pipeline for SmartBiz application:
    1. Clone repository
    2. Run tests
    3. Build Docker image
    4. Deploy to Kubernetes
  workspaces:
    - name: shared-workspace
      description: Shared workspace for pipeline tasks
    - name: docker-credentials
      description: Docker registry credentials
      optional: true
  params:
    - name: git-url
      description: Git repository URL
      type: string
      default: https://github.com/seadavdic/ClaudeAI.git
    - name: git-revision
      description: Git revision (branch, tag, or commit SHA)
      type: string
      default: main
    - name: image-name
      description: Container image name (without tag)
      type: string
      default: docker.io/seadavdic/smartbiz-api
    - name: image-tag
      description: Container image tag
      type: string
      default: latest
    - name: deployment-name
      description: Kubernetes deployment name
      type: string
      default: smartbiz-api
    - name: deployment-namespace
      description: Kubernetes namespace
      type: string
      default: smartbiz
  tasks:
    # Task 1: Clone the repository
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    # Task 2: Run tests
    - name: run-tests
      taskRef:
        name: python-test
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: python-version
          value: "3.11"
        - name: requirements-file
          value: "apps/smartbiz-api/requirements.txt"
        - name: test-path
          value: "apps/smartbiz-api/tests/"

    # Task 3: Build container image
    - name: build-image
      taskRef:
        name: build-image
      runAfter:
        - run-tests
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: image
          value: "$(params.image-name):$(params.image-tag)"
        - name: dockerfile
          value: "apps/smartbiz-api/Dockerfile"
        - name: context
          value: "apps/smartbiz-api"

    # Task 4: Deploy to Kubernetes
    - name: deploy-to-cluster
      taskRef:
        name: deploy-to-kubernetes
      runAfter:
        - build-image
      params:
        - name: deployment-name
          value: $(params.deployment-name)
        - name: namespace
          value: $(params.deployment-namespace)
        - name: image
          value: "$(params.image-name):$(params.image-tag)"
        - name: container-name
          value: smartbiz-api

  finally:
    # Cleanup or notification tasks can go here
    - name: notify-status
      params:
        - name: pipeline-status
          value: $(tasks.status)
      taskSpec:
        params:
          - name: pipeline-status
        steps:
          - name: notify
            image: curlimages/curl:latest
            script: |
              #!/bin/sh
              echo "Pipeline completed with status: $(params.pipeline-status)"
              # Add Slack/Telegram notification here if needed
