---
# PersistentVolumeClaim for Pipeline Workspace
# This provides shared storage for pipeline tasks
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-workspace-pvc
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path  # k3s default storage class
